export default {
    headerImage: require('../../assets/images/header-img.png'),
    userIcon: require('../../assets/images/profile-icon.png'),
    hemBurger: require('../../assets/images/hemburger.png'),
    orImage: require('../../assets/images/or.png'),
    logo: require('../../assets/images/logo.png'),
    userProfile: require('../../assets/images/userProfile.png'),
    bgImg: require('../../assets/images/bgImg.png'),
    addDreanIcon: require('../../assets/images/addDream.png'),
    analyzeDreamIcon: require('../../assets/images/analyzeDream.png'),
    donateIcon: require('../../assets/images/donate.png'),
    symbolIcon: require('../../assets/images/symbol.png'),
    dreamCircleIcon: require('../../assets/images/dreamCircleIcon.png'),
    dreamJournalIcon: require('../../assets/images/dreamJournal.png'),
    homeIcon:require('../../assets/images/home-icon.png'),
    donateTabIcon:require('../../assets/images/donate-icon.png'),
    searchIcon:require('../../assets/images/search-icon.png'),
    profileIcon:require('../../assets/images/tab-profile-icon.png'),
    addIcon:require('../../assets/images/add-icon.png'),
    googleImg:require('../../assets/images/google-icon.png'),
    contactUs:require('../../assets/images/contact-us.png'),
    question:require('../../assets/images/quesntion.png'),
    loginBg:require('../../assets/images/login-bg.png'),
    loginIcon:require('../../assets/images/login-icon.png'),
    blogIcon:require('../../assets/images/blog.png'),
}